name: Build and deploy package

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest                      # instala o terminal ubunto

    steps:
      - uses: actions/checkout@main

      - name: Set up .NET Core                      # instala o dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'

      - name: build with dotnet                     # constroi a aplicação
        run: dotnet build --configuration Release

      - name: Test                                  # faz um teste na aplicação
        run: dotnet test

      - name: Create the Package                    #Cria e faz um pacote da aplicação
        run: dotnet pack --configuration  Release

      - name: Publish
        env:
          NUGET_API_KEY: ${{secrets.NUGET_TOKEN_SILVIO}}   #secrets.NUGET_TOKEN_SILVIO: a chave está salva no github
        run: dotnet nuget push "MoneyExtension/bin/Release/*.nupkg" -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json

   