name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest                      # instala o terminal ubunto
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@main

    - name: Set up .NET Core                      # instala o dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'

    - name: Add GitHub Packages Source
      run: dotnet nuget add source https://nuget.pkg.github.com/SilvioSebastiany/index.json --n github -u silviosebastiany -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

    - name: Build with dotnet                     # constroi a aplicação
      run: dotnet pack --configuration Release

    - name: Create the Package                    #Cria e faz um pacote da aplicação
      run: dotnet pack --configuration  Release

    - name: Publish     #GITHUB_TOKEN: é uma variavel especial, para configuração de autenticação
      run: dotnet nuget push "bin/Release/*.nupkg" -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/SilvioSebastiany/index.json

   