name: Build and deploy

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest                      # instala o terminal ubunto
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3                   # Use a versão mais recente da action (v3)

    - name: Set up .NET Core                      # instala o dotnet
      uses: actions/setup-dotnet@v3               # Use a versão mais recente da action (v3)
      with:
        dotnet-version: '7.0.x'

    - name: Add GitHub Packages Source
      run: dotnet nuget add source https://nuget.pkg.github.com/SilvioSebastiany/index.json -n github -u ${{ github.actor }} -p ${{ secrets.NUGET_TOKEN_SILVIO }} --store-password-in-clear-text

    ##- name: Restore Dependencies
    ##  run: dotnet restore

    - name: Build Application
      run: dotnet build --configuration Release --no-restore

    - name: Create the Package                    #Cria e faz um pacote da aplicação
      run: dotnet pack --configuration Release --no-build

    - name: Publish Package     #GITHUB_TOKEN: é uma variavel especial, para configuração de autenticação
      run: dotnet nuget push "bin/Release/*.nupkg" -k ${{ secrets.NUGET_TOKEN_SILVIO}} -s https://nuget.pkg.github.com/SilvioSebastiany/index.json --skip-duplicate --timeout 600

   
